version: "3.9"

services:

  backend:
    build:
      context: ./backend
    container_name: payflow-backend
    restart: unless-stopped

    expose:
      - "8080"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/payflow
      DB_USERNAME: payflow
      DB_PASSWORD: payflow

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

      REDIS_HOST: redis
      REDIS_PORT: 6379

      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
      RAZORPAY_WEBHOOK_SECRET: ${RAZORPAY_WEBHOOK_SECRET}

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    networks:
      - payflow-network

  postgres:
    image: postgres:17
    container_name: payflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: payflow
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payflow -d payflow"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - payflow-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: payflow-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - payflow-network

  redis:
    image: redis:8-alpine
    container_name: payflow-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - payflow-network

  prometheus:
    image: prom/prometheus:latest
    container_name: payflow-prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - payflow-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: payflow-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus

    networks:
      - payflow-network

  nginx:
    image: nginx:latest
    container_name: payflow-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - payflow-network

networks:
  payflow-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: