spring:
  application:
    name: payflow

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

  api-docs:
    path: /api-docs

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}

payflow:
  webhook:
    signature-verification-enabled: false

  rate-limit:
    limit: 100
    window-seconds: 60

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - circuitbreakers
          - circuitbreakerevents
          - retries
          - retryevents
          - bulkheads
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      razorpayGateway:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      razorpayGateway:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - com.harsh.payflow.payment.exception.PaymentGatewayException

  bulkhead:
    instances:
      razorpayGateway:
        max-concurrent-calls: 10
        max-wait-duration: 0